apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace "expo.modules.gametokengine"
    compileSdkVersion 35

    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 35
        versionCode 1
        versionName "1.0.0"

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation project(':expo-modules-core')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.24"

    // Google Filament PBR & glTF/GLB Mocap Engine
    api "com.google.android.filament:filament-android:1.56.0"
    api "com.google.android.filament:gltfio-android:1.56.0"
    api "com.google.android.filament:filament-utils-android:1.56.0"
}
